name: Frontend Tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:23-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Connect to PostgreSQL
        working-directory: ./api
        run: pnpm prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/tests
      
      - name: Install Backend Dependencies
        working-directory: ./api
        run: pnpm install
      
      - name: Run Backend
        working-directory: ./api
        run: pnpm dev
      
      - name: Install Frontend Dependencies
        working-directory: ./web
        run: pnpm install
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./web
          build: pnpm build
          start: pnpm preview
          browser: firefox